apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mcha
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/mleonova-tenant/devfile-sample-code-with-quarkus/devfile-sample-mcha@sha256:ecbd347568ca6e5dcaa58476722eedc4d12ea35913bacac96496ae0dadb38594
        name: my-nodejs
        resources: {}
status: {}
